[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "k2-inventory"

[services.variables]
USE_SCHEDULER = "false"
TZ = "America/Chicago"